### ISSUE TITLE
Fails if category is missing

### ISSUE THREAD

**Issue by vparpoil** [jbierfeldt/podcast-feed-parser#11]
If Category is missing from podcast file, parsing fails
```
TypeError: Cannot read property 'map' of undefined
    at categories (/node_modules/podcast-feed-parser/index.js:172:53)
    at exports.getInfo (/node_modules/podcast-feed-parser/index.js:291:36)
    at options.fields.meta.forEach (/node_modules/podcast-feed-parser/index.js:314:18)
    at Array.forEach (<anonymous>)
    at createMetaObjectFromFeed (/node_modules/podcast-feed-parser/index.js:306:23)
    at Object.exports.getPodcastFromFeed (/node_modules/podcast-feed-parser/index.js:464:18)
```

Example of RSS that breaks : [https://api.octopus.saooti.com/rss/emission/63](https://api.octopus.saooti.com/rss/emission/63)

Since [Atom:category is optional](https://tools.ietf.org/html/rfc4287#page-18), it should work without

**Comment by vparpoil** [comment]
Fixed in last release
